### ISSUE TITLE
Need to import multiple sheets from a single file

### ISSUE THREAD

**Issue by AntoineKMS** [Alipsa/spreadsheets#1]
Hi,

I have an excel file with at least a dozen of sheets and need to extract all of them.

I have a working method of calling the 'importSpreadsheet' method each time for each sheet, but I timed that it takes arround 30 seconds for each call, because each time I call 'importSpreadsheet', the excel file need to be opened. (the file is arround 10Mo)

My script takes arround half a second to complete, but the part where it is loading the excel file takes several minutes.

I believe calling a single function for importing multiple sheets would speed up the process by a lot.

I use to have the libreary readxl on Rstudio but cannot make it work on Renjin.

the function to load all sheets was looking like this :

```
  library(readxl)    

  read_excel_allsheets <- function(filename) {
    sheets <- readxl::excel_sheets(filename)
    x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
    names(x) <- sheets
    x
  }
```
This function takes about 15 seconds for the same file, and give as an output a dataframe of dataframes (one for each sheet from the excel file).

I was wondering if you think it would be possible to have the same functionnality.

Thanks for your time.

**Comment by perNyfelt** [comment]
I think something like this should be doable. What about an api that looks like this:
```r
importSpreadsheets <- function(filePath, sheets = c("Sheet1","Sheet2","Sheet3"), importAreas = list("Sheet1"=c(1, 1212, 1, 17), "Sheet2"=c(5,123,2,10), "Sheet3"=c(1,345, 2, 34)), firstRowAsColumnNames = list("Sheet1"=FALSE, "Sheet2"=TRUE, "Sheet3"=TRUE) )
```
Where importAreas values are startRow, endRow, startColumn, endColumn respectively?

I will return a named list of a sheet name and the corresponding data.frame. i.e. to get the data.frame for sheet2 you would do:
```r
sheets <- importSpreadsheets(
    filePath=paste0(getwd(), "/results.xslx"),
    sheets = c("Sheet1","Sheet2","Sheet3"), 
    importAreas = list(
        "Sheet1"=c(1, 1212, 1, 17), 
        "Sheet2"=c(5,123,2,10), 
        "Sheet3"=c(1,345, 2, 34)
    ), firstRowAsColumnNames = list(
        "Sheet1"=FALSE, 
        "Sheet2"=TRUE, 
        "Sheet3"=TRUE
    )
)
sheet2 <- sheets[["sheet2"]]
```

Are you OK with running in Java 11 or higher or do i need to make something available for java 8?

**Comment by AntoineKMS** [comment]
Yes this looks very good, similar to your already existing exportspreadsheets function.

I am okay with Java 11 because I am also running the latest version of Ride on java 11.

Thanks a lot for your help.

**Comment by AntoineKMS** [comment]
I am not sure If I should post it here, but I have another very small issue with this library. It's about the endRow, endColumn variables. 
Would it be possible to have a default value that would just take as many rows and columns as there are in the sheet ?

It is very good to be able to tweak those parameters for when we only want certains parts of the sheet, but I think  it would be good to have an option/ a default parameter to just take the whole sheet.

Thanks you.

**Comment by perNyfelt** [comment]
I'll look at it. I think this is reasonably well supported in Apache POI for Excel but there is nothing like this for SODS (Libre/Open Office) so I'll have to do some manual probing for that which might be slow. Maybe a magical constant e.g. setting the endRow and endColumn to -1 or similar would be a decent way to support this.

**Comment by perNyfelt** [comment]
Support for this added 1.3.4 that was just release. -1 to support "unknown" endRow and endColumn variables is not yet implemented. I'll open a separate issue for that.
